# generate names of const
import os

home = os.getenv('HOME')
const_src = os.path.join(home, 'git-clone/jallib/include/jal/constants_jallib.jal')

names = []
with open(const_src) as f:
    for line in f:
        try:
            comment_col = line.index('--')
        except ValueError:
            comment_col = -1

        if(comment_col > -1):
            line = line[0:comment_col]

        line = line.rstrip()

        if line == '':
            continue
        sa = line.split()
        names.append(sa[-3])
        # print('"' + sa[-3] + '"')

names = list(dict.fromkeys(names))  # remove duplicates


out_path = 'jallib-consts.el'
header_lines = ''';;; This file was generated by jallib_consts.py,
;;; and is intended to be "require"d from jal-mode.el.

(setq jal-mode-constants
    \'(;; from jallib/include/jal/constants_jallib.jal
'''

from pathlib import Path
footer_lines = f'''      ))

(provide \'{Path(out_path).stem})
;;; {out_path} ends here
'''

with open(out_path, mode='w') as f:
    f.write(header_lines)

    names = ['      "' + x + '"\n' for x in names]
    f.writelines(names)

    f.write(footer_lines)
